### ISSUE TITLE
Doesn't work on RC2

### ISSUE THREAD

**Issue by inexuscore** [damienbod/AspNet5Localization#12]
Hi Damien :godmode:

Came across your repo, cool package and thanks for sharing :tada:.
However I'm having trouble using this in a RC2 project. Everything's alright except when I try to add and apply the migration. The library code is integrated properly, and everything is set up according to your documentation. Here's the migration error:

`warning NU1012: Dependency conflict. Microsoft.EntityFrameworkCore                                                                                                                1.0.0-rc3-21343 expected Microsoft.Extensions.Logging >= 1.0.0-rc3-21343 but go                                                                                                            t 1.0.0-rc2-final`

And a little more down in the stack trace:
`Could not load type 'Microsoft.Extensions.DependencyInjection.ServiceCollectionE                                                                                                               xtensions' from assembly 'Microsoft.Extensions.DependencyInjection, Version=1.0.                                                                                                               0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'`

I think if you rebuild the package on RC2, this issue will be resolved.

**Comment by inexuscore** [comment]
Hello again,
I've updated the package to `"Localization.SqlLocalizer": "1.0.1"` and the first dependency conflict is resolved. However the second issue is still present when i try to add this migration:
`dotnet ef migrations add AddSqlLocalization --context LocalizationModelContext`

Any ideas? :8ball:

**Comment by inexuscore** [comment]
Resolved :godmode:
I had a mixture of RC1, beta and RC2 dependencies listed in `project.json`. Just removed all version identifiers and replaced them with `1.0.0-*`. After that a package restore and voila, works like a charm :game_die:

**Comment by damienbod** [comment]
Hi @inexuscore 

great, if you have any improvements or suggestions of how to improve this, let me know. 

Thanks and greetings Damien

**Comment by inexuscore** [comment]
@damienbod Greetings. Sure thing, I'm tinkering with i18n in ASP.NET Core and your package. I'll keep contact :tada:
