### ISSUE TITLE
Issues with RC1

### ISSUE THREAD

**Issue by nickgru** [damienbod/AspNet5Localization#2]
Hello,

I was trying to get localization to work with RC1 but have run into issues with mine as well as your project. It seems to not able to return the resource. When it tries to get the resource "Name" it just returns Name because it is erroring out with the ResourceManagerStringLocalizer. I've tried your project running in VS and Console and still does not return the appropriate resource. I'm not sure what I am missing here.

When I to evaluate in in debug I get this: 
?_htmlLocalizer["Name"];
{Name}
Name: "Name"
ResourceNotFound: true
Value: "Name"

Thanks for your help.

**Comment by damienbod** [comment]
Hi @nickgru 

Yes, I have created an issue here:

https://github.com/aspnet/Localization/issues/150#issuecomment-158188724

Will let you know, when I get it working again.

Greetings Damien

**Comment by damienbod** [comment]
Hi @nickgru

This is fixed now using magic strings with an empty class and special resource naming...

**Comment by damienbod** [comment]
Let me know if you have a problem

greetings Damien

**Comment by nickgru** [comment]
Thanks @damienbod, I've been following the thread on the issue you created.  I feel the same as you, this solution does not feel right to me.  I'm not sure why the concept of having shared resources seems wrong to them.  

Ideally when I hire a translator to translate my resources file, I would like them to be able to translate one large file instead of many many files, especially when there are likely repeated words and phrases in there.  

Thanks for keeping active on this.

**Comment by damienbod** [comment]
Thanks for your feedback
Greetings Damien
