### ISSUE TITLE
Realtime update?

### ISSUE THREAD

**Issue by jimmy84** [damienbod/AspNet5Localization#21]
I notice the localize text wasn't shown on the UI every time when I updated the localize text in database. Is this intentional or am I missing something? Is there anyway I can make it to updated in real time? 

I am using SQL Server so I have the below instead

```
services
	.AddDbContext<ApplicationDbContext>(options =>
		options.UseSqlServer(Configuration.GetConnectionString("DefaultConnection"))
	)
	.AddDbContext<LocalizationModelContext>(options => 
		options.UseSqlServer(Configuration.GetConnectionString("DefaultConnection"))
	);
```

I also created the LocalizationRecords table in my model

```
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebApp.Models
{
    public class LocalizationRecords
    {
        public long ID { get; set; }

        public string Key { get; set; }

        public string ResourceKey { get; set; }

        public string Text { get; set; }

        public string LocalizationCulture { get; set; }

        public DateTime UpdatedTimestamp { get; set; }
    }
}
```

**Comment by damienbod** [comment]
If you update the text directly in the database, the texts will not be updated in the application until it is restarted, use a static cache for performance. If the texts are updated using the import in the lib, the cache values are reset

If you have suggestions on how to improve this, let me know and I, we can update it

Greetings Damien

**Comment by jimmy84** [comment]
I'm not expert in this, but is it possible to have something like, having a function to issue/trigger the cache to be updated through controller, so that this only happen when user perform such action.

**Comment by damienbod** [comment]
If you use the IStringExtendedLocalizerFactory interface, you can reset the cache

**Comment by jimmy84** [comment]
Ok. I'll give it a try.

**Comment by damienbod** [comment]
@jimmy84 
http://localizationsqllocalizer.readthedocs.io/en/latest/cachereset.html

**Comment by jimmy84** [comment]
Oh. Ok. Thx!

**Comment by jimmy84** [comment]
I tried this with a simple controller, but doesn't seems to work.

```
using Localization.SqlLocalizer.DbStringLocalizer;

namespace SampleApp.Controllers
{
	public class LocalizationController : Controller
	{       
        private readonly IStringExtendedLocalizerFactory _StringFactory;

        public LocalizationController(IStringExtendedLocalizerFactory stringFactory)
        {
            _StringFactory = stringFactory;
        }
		
		[HttpGet]
        public IActionResult Reset()
        {
            try
            {
                _StringFactory.ResetCache();                

                return RedirectToAction("Index", "Home");
            }
            catch (Exception e)
            {
                return RedirectToAction("Index", "Error");
            }
        }
	}
}
```

**Comment by damienbod** [comment]
Hi @jimmy84, just tested this, this does work, you need to refresh your browser cache. The reset cache method just refreshes the server cache, if it's called. 

Greetings Daemin
