### ISSUE TITLE
When all resx files have culture it does not work

### ISSUE THREAD

**Issue by JoeOM** [damienbod/AspNet5Localization#3]
Dear Damien

I read through your post on github asp.net localization and totally agree with you on the stupid empty class etc. I did open my own ticket as it seems it still does not work... With your example I have made a few changes to demonstrate. Please see image for what I did. :)

If you agree with me please add your voice on that post as well. We should stop this localization rookie absurdity.

![test](https://cloud.githubusercontent.com/assets/16026395/11415209/23dedc7e-9454-11e5-85fe-86125e3f7026.png)

**Comment by damienbod** [comment]
Hi Joe

Looks ok.

Three possible causes:

- When the resx class is regenerated, the designer.cs class created is internal and not public. This needs to be changed manually to public. Tooling bug.
- The localization only works from the console. Tooling bug
- You might need a default resource resx file for this to work. Only guessing here, as I have not invested any time into research how the magic string resolve works in the default ASP.NET 5 implementation.

Greetings Damien

**Comment by chemitaxis** [comment]
I have exactly same error here...

**Comment by chemitaxis** [comment]
Ok, I solved it... I will do a full complete example tomorrow.

I have created a _ViewImports, and add it:

```
@addTagHelper "*, Microsoft.AspNet.Mvc.TagHelpers"
@using System.Threading.Tasks
@using AspNet5Localization
@using AspNet5Localization.Resources
@using Microsoft.AspNet.Mvc.Localization
@using Microsoft.Extensions.Localization
@inject IStringLocalizer<AmazingResource> SR

```
After, I have created a HomeController and Views/Home/Index.cshlm file.

Like I have injected in my Views the IStringLocalizer<AmazingResource> SR I can use it in my Razor Views using just:
```
@SR["Name"]
```

Thanks for this amazing example... Great works!!

**Comment by israelito3000** [comment]
I know is April now and maybe this implementation is not updated, but I loaded the example, running it but it never get the data from the localized resource, actually I couldn't found any example on the web in which localization works. Could you give me a path?

You talked about Designer file (autogenerated per resource) actually my Vs is not generating those files, unless I create a new resx file by myself.

**Comment by damienbod** [comment]
Hi @israelito3000 

This example does work, but only when started from the console. The Visual Studio tooling bugs are still not fixed. Once RC2 is released, I will update this repo. Localization will not work correctly, until RC2 is released. 

Hope this helps

Greetings Damien

**Comment by damienbod** [comment]
Fixed now in RC2 tooling
