### ISSUE TITLE
AngularLocalizaionAspNetCore Solution does not build in VS2017 Enterprise . Can you help me?

### ISSUE THREAD

**Issue by pjlay** [damienbod/AspNet5Localization#33]
Severity	Code	Description	Project	File	Line	Suppression State
Error	TS2688	Build:Cannot find type definition file for 'node'.	AngularLocalizationAspNetCore	C:\Users\pjlay\Documents\Visual Studio 2017\Projects\Angular2LocalizationAspNetCore-master\src\AngularLocalizationAspNetCore\tsc	1

**Comment by damienbod** [comment]
You might need to install nodejs. The nodejs deployed with VS2017 is an old one. You need to configure VS to use the nodejs installed on the path
Then try from the commnad line to see if VS is configured correctly or if your missing something.

> npm install
> npm run build-production
> dotnet restore
> dotnet build

Greetings Damien
