### ISSUE TITLE
How-to(s): Return per culture JSON / Form Validation / Identity Culture in REST API

### ISSUE THREAD

**Issue by ericbrunner** [damienbod/AspNet5Localization#36]
Hi Damien,

Is it possible to get all localized strings for a specific culture as a serialized JSON dictionary (like your CSV Export sample in JSON format)? 

I want to fetch the JSON localized strings in one go to build my client side UI, and don't get them as a kind of ViewBag/ViewData for each Razor View request.

I would like to set the culture in the REST API Controller through a Culture property I specified the culture as a member of my Identity user (Asp.net Core Identity via HttpContext.User).

 I can only find solutions via query string, culture route, or http header. Is that possible? 

So what I would like to do is something like that:

[HttpGet]
public async Task<string> Get() {

var user = await userManager.GetUserAsync(user);
var myString = localizer[user.Culture, textKey];

return myString;
}

One question regarding DataAnnotations:

Could you provide one sample with a Razor View that contains a form and a ViewModel with validation texts that shows the multilingual feature ? I could only find the BoxController sample, maybe I think to complicated but I didn't understand how it would work on a form.

Thanks,
Eric

**Comment by damienbod** [comment]
To change to json, you just need to change the controller from the example. I force csv, you could remove this and request a json format.

Greetings Damien
